language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql-server

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - vendor/bin/phpunit --verbose
  - phpcs --standard=PSR2 --extensions=php --warning-severity=0 ./src

after_script:
  - ./vendor/bin/coveralls -v